services:
  - type: web
    name: pdf-processor-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: PORT
        value: 10000
    healthCheckPath: /api/health 